//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDWINFORMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        public int almacenID { get; set; }
        public string almacenNombre { get; set; }
        public string almacenDireccion { get; set; }
        public string ciudad { get; set; }
        public string estado { get; set; }
        public string codigoPostal { get; set; }
    }
}
