//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDWINFORMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        public int cargoID { get; set; }
        public string cargoDescripcion { get; set; }
        public short nivelMinimo { get; set; }
        public short nivelMaximo { get; set; }
    }
}
