//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDWINFORMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class titulo
    {
        public int tituloId { get; set; }
        public string tituloName { get; set; }
        public string Genero { get; set; }
        public int editorialID { get; set; }
        public decimal precio { get; set; }
        public decimal adelanto { get; set; }
        public int regalias { get; set; }
        public int ventaAnual { get; set; }
        public string notas { get; set; }
        public System.DateTime fechaPublicacion { get; set; }
    
        public virtual Editorial Editorial { get; set; }
    }
}
